name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Compile Kotlin
        run: ./gradlew compileKotlin compileJava -x test
      - name: Build web
        run: cd web && npm ci && npm run build
